server:
  port: 0
spring:
  application:
    name: auth

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    status-page-url-path: /
    metadata-map:
      user:
        name: actuator
        password: 123456
      
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"