server:
  port: 0
spring:
  application:
    name: products
  datasource:
    url: jdbc:h2:mem:products #Trocar para o modo físico
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      org.hibernate.envers.audit_table_suffix: _aud
      org.hibernate.envers.do_not_audit_optimistic_locking_field: false
      org.hibernate.enver.audit_strategy: org.hibernate.envers.strategy.internal.ValidityAuditStrategy
      hibernate:
        ddl-auto: none
        temp:
          use_jdbc_metadata_defaults: false 
  redis:
    host: localhost
    port: 6379
  session:
    store-type: redis
    redis:
      namespace: spring:session
  h2:
    console:
      enabled: true
      path: /h2
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka